name: searchable_paginated_dropdown
description: Flutter searchable dropdown widget which can be used also with paginated requests.
version: 1.2.0
homepage: https://github.com/mdikcinar/searchable_dropdown

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
